name: FT81x Arduino Driver CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: build example sketches
      run: bash ci/build.sh
